name: Android Debug Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Run Unit Tests
        run: ./gradlew test
        env:
          ADMOBAPPID_DEBUG: ${{ secrets.ADMOB_APP_ID_DEBUG }}
          ADMOB_BANNER_ID_DEBUG: ${{ secrets.ADMOB_BANNER_ID_DEBUG }}
          ADMOB_INTERSTITIAL_ID_DEBUG: ${{ secrets.ADMOB_INTERSTITIAL_ID_DEBUG }}
          ADMOB_REWARDED_ID_DEBUG: ${{ secrets.ADMOB_REWARDED_ID_DEBUG }}

      - name: Test Report
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: Unit Test Results
          path: "**/test-results/**/*.xml"
          reporter: java-junit

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: unit-test-reports
          path: app/build/reports/tests/
